#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Thu Aug 13 02:32:29 GMT 2026
android.nonTransitiveRClass=true
org.gradle.daemon.idletimeout=10800000
kotlin.code.style=official
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
